version: '3.8'

services:
  app:
    image: nemanjamitic/blog:0.0.1
    container_name: blog
    # all that is needed to build prod live image
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SITE_HOSTNAME
      - PORT
    networks:
      - proxy

networks:
  proxy:
    external: true
