version: '3.8'

services:
  astro-blog:
    image: nemanjamitic/astro-blog:0.0.1
    container_name: astro-blog
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SITE_HOSTNAME
      - PORT
    networks:
      - proxy

networks:
  proxy:
    external: true
